# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ffe87167c189842aa24b2144cabcecc170c7d5e3b99c10b6c1de1ea8e50280217eb9e9e956282606f271f22c1d16cca6467ba0aa6d3855f48487efc8b7eec79

test:
  secret_key_base: 1c95fc9194839b1ea9d65f122acd251e169b36da3a168847b84d71ddc81f58f33e100240d9ad1a52d8be19f55e3ded21e48e8257883f7070d504a157ffb67dd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
